In [2]:
import pandas as pd

In [8]:
richest = pd.read_csv('TopRichestInWorld.csv', usecols=['Name']).squeeze() # el squeeze lo que hace es convertirlo en Series
richest

0                     Elon Musk
1                    Jeff Bezos
2      Bernard Arnault & family
3                    Bill Gates
4                Warren Buffett
                 ...
96             Vladimir Potanin
97         Harold Hamm & family
98                 Sun Piaoyang
99           Luo Liguo & family
100                   Peter Woo
Name: Name, Length: 101, dtype: str

In [4]:
type(richest)

pandas.Series

In [5]:
richest.to_csv('test_richest.csv', index=False)

In [9]:
people = pd.read_csv('test_richest.csv')
people

                         Name
0                   Elon Musk
1                  Jeff Bezos
2    Bernard Arnault & family
3                  Bill Gates
4              Warren Buffett
..                        ...
96           Vladimir Potanin
97       Harold Hamm & family
98               Sun Piaoyang
99         Luo Liguo & family
100                 Peter Woo

[101 rows x 1 columns]

In [13]:
pd.read_csv('test_richest.csv').tail(10)

                        Name
91   Savitri Jindal & family
92               Wang Wenyin
93                 Li Xiting
94            Stefan Persson
95               Steve Cohen
96          Vladimir Potanin
97      Harold Hamm & family
98              Sun Piaoyang
99        Luo Liguo & family
100                Peter Woo

In [ ]:
richest.sort_values(
                        axis=0,
                        ascending=True,
                        kind='quicksort',
                        na_position= 'last',
                        ignore_index=True
                    )

0           Abigail Johnson
1          Alain Wertheimer
2              Alice Walton
3            Amancio Ortega
4            Andrew Forrest
               ...
96           Warren Buffett
97         William Lei Ding
98     Yang Huiyan & family
99             Zhang Yiming
100          Zhong Shanshan
Name: Name, Length: 101, dtype: str

### Ahora vamos con otras columnas

In [18]:
richestv2 = pd.read_csv('TopRichestInWorld.csv', usecols=['Industry']).squeeze()
richestv2

0                 Automotive
1                 Technology
2           Fashion & Retail
3                 Technology
4      Finance & Investments
               ...
96           Metals & Mining
97                    Energy
98                Healthcare
99             Manufacturing
100              Real Estate
Name: Industry, Length: 101, dtype: str

In [20]:
richestv2.value_counts()

Industry
Fashion & Retail         18
Technology               15
Finance & Investments    13
Metals & Mining           9
Food & Beverage           8
Automotive                7
Diversified               6
Manufacturing             5
Healthcare                5
Media & Entertainment     4
Real Estate               3
Telecom                   2
Logistics                 2
Energy                    2
Gambling & Casinos        1
Service                   1
Name: count, dtype: int64

In [23]:
richestv2.value_counts(normalize=True,
                       ascending=True,
                       dropna=True)

Industry
Gambling & Casinos       0.009901
Service                  0.009901
Telecom                  0.019802
Logistics                0.019802
Energy                   0.019802
Real Estate              0.029703
Media & Entertainment    0.039604
Manufacturing            0.049505
Healthcare               0.049505
Diversified              0.059406
Automotive               0.069307
Food & Beverage          0.079208
Metals & Mining          0.089109
Finance & Investments    0.128713
Technology               0.148515
Fashion & Retail         0.178218
Name: proportion, dtype: float64

In [27]:
richest = pd.read_csv('TopRichestInWorld.csv', usecols=['Age']).squeeze()
richest

0      50
1      58
2      73
3      66
4      91
       ..
96     61
97     76
98     63
99     66
100    75
Name: Age, Length: 101, dtype: int64

In [28]:
richest.value_counts(bins=3)

(51.333, 72.667]    47
(72.667, 94.0]      39
(29.935, 51.333]    15
Name: count, dtype: int64

### POSICIONES

In [ ]:
richest.head(10) #top x

0    50
1    58
2    73
3    66
4    91
5    49
6    48
7    77
8    66
9    64
Name: Age, dtype: int64

In [ ]:
richest[[1,2,15]] # especificas

1     58
2     73
15    73
Name: Age, dtype: int64

In [ ]:
richest[5:10] # de 5 a 10

5    49
6    48
7    77
8    66
9    64
Name: Age, dtype: int64

In [32]:
richest[0:21:5] # de 0 a 21 skipeando 5

0     50
5     49
10    59
15    73
20    86
Name: Age, dtype: int64

In [33]:
richest[:10] # todo hasta 10

0    50
1    58
2    73
3    66
4    91
5    49
6    48
7    77
8    66
9    64
Name: Age, dtype: int64

In [ ]:
# richest[-1] # asi no

In [34]:
richest[-1:] # asi si, con : al final, para acceder al -x posicion

100    75
Name: Age, dtype: int64

#### LO VEMOS CON LA TABLA CSV